Fix query grammar for multi-joins. CBL-1560
couchbase/couchbase-lite-core pull request #1110
Opened 2021-01-21 20:14 UTC by jianminzhao

Allow second JOIN to consume white spaces. Added test cases that would fail without this fix.

2021-01-21 22:02 UTC, borrrden requested changes
Just to be consistent with the original ticket could you add or modify these tests to use LEFT JOIN instead of just JOIN?

2021-01-21 22:09 UTC, jianminzhao commented
@borrrden will do.

2021-01-22 01:30 UTC, borrrden approved these changes

2021-01-22 22:28 UTC, snej approved these changes

2021-01-22 22:29 UTC, merged