Fix MSVC build issue, and implicit dependency
couchbase/couchbase-lite-core pull request #1165
Opened 2021-04-21 23:01 UTC by borrrden

There is a bug in the MSVC 15.x compiler that Microsoft will not fix that prevents the use of guaranteed copy elision with deleted move constructors in some cases.  Use a workaround until upgrade to 16.x.

Also don't force define the cert requesting stuff in C4Certificate since it creates an additional dependency on another library when building consumers of the library.

2021-04-23 00:14 UTC, borrrden commented
Flaky tests are flaky....hard to keep track of which got fixed in which branch.  Need to merge the dev branch asap.

2021-04-23 16:24 UTC, jianminzhao approved these changes

2021-04-23 16:49 UTC, pasin approved these changes

2021-04-26 20:32 UTC, snej requested changes
I'd prefer to use ifdefs to restrict this change to MSVC; also, could you add a comment describing the reason for the workaround?

2021-04-28 00:30 UTC, merged