CBD-4043: Mobile 3.0 BSL
couchbase/couchbase-lite-core pull request #1254
Opened 2021-09-27 15:39 UTC by udkyo

Updates for master branch

2021-09-27 21:46 UTC, borrrden requested changes
I don't see the licenses folder in this commit.  Am I missing it?

2021-09-28 07:03 UTC, udkyo commented
Whoops, thank you, I hadn't checked it in. The new commit has the missing files.

2021-09-28 16:45 UTC, snej approved these changes

2021-09-28 17:03 UTC, pasin approved these changes

2021-09-28 22:01 UTC, borrrden approved these changes

2021-09-28 22:03 UTC, borrrden commented
I merged the downstream fleece, so could you bump the submodule on your fork to the latest fleece master @udkyo ?

2021-09-29 21:38 UTC, djpongh approved these changes

2021-10-05 01:26 UTC, merged