CBL-2658 : manage WebSocket lifecycle
couchbase/couchbase-lite-core pull request #1390
Opened 2022-03-03 00:47 UTC by jianminzhao

From the standpoint of the lifecycle, a WebSocket can have 4 states: Opening, Opened, Closing, and Closed. These states can only progress monotonically: it can only transition to the following states in that order.

2022-03-03 17:48 UTC, jianminzhao commented
Author's notes: the timers after closeSocket() and requestClose() are new. I believe, in that meeting, we wanted to add the timer to wait for c4socket_closed(). Currently, we only add timer to wait for the echoing of "close" (op) message between local and remote, whereas closeSocket and socket_closed are echoed between Core and Platform within the local.
Just put it here as a question to the reviewers, since closeSocket/requestClose signals Platform that there will be no more use of the socket, all Platform should see to is to not call c4socket_xyz except for c4socket_closed, what does Platform would wait for to echo back "closed?"

2022-03-03 18:09 UTC, snej commented
> closeSocket/requestClose signals Platform that there will be no more use of the socket,

`requestClose` signals that LiteCore won't write to the socket anymore. But messages might still arrive that were sent by the peer before it receives the CLOSE message. The platform should relay those to LiteCore, i.e. should call `c4socket_received`.

2022-03-03 18:34 UTC, jianminzhao commented
So, after requestClose(), Platform needs to negotiate with the remote to close the socket, and meanwhile, all messages received from remote before it is closed should be relayed to LiteCore. Therefore, these is an indefinite period before Platform can echo back "closed," right?
Therefore we should allow timeout after closeSocekt/requestClose. With this PR, if Platform spend too much time negotiating the close, when timed-out, we will move to onClose().

2022-03-03 23:50 UTC, borrrden requested changes
In general I'd like to push for "log when code returns early" to give these unusual code paths more visibility.  It's been my experience that we have been confused by these before since they happen rarely and don't leave any evidence behind.

2022-03-04 01:50 UTC, jianminzhao commented on Networking/WebSockets/WebSocketImpl.cc
> +        _socketLCState.store(SOCKET_OPENING);
I think they are equivalent. The socket's life starts here.

2022-03-04 01:50 UTC, jianminzhao commented on Networking/WebSockets/WebSocketImpl.cc
> +        if (curState == SOCKET_CLOSED || curState == SOCKET_CLOSING) {
will do

2022-03-04 01:50 UTC, jianminzhao commented on Networking/WebSockets/WebSocketImpl.cc
> +        int curState = atomic_exchange(&_socketLCState, (int)SOCKET_CLOSING);
Good catch. Ought to use compare_exchange. Same problem in the above function

2022-03-04 01:50 UTC, jianminzhao commented on Networking/WebSockets/WebSocketImpl.cc
> +            case SOCKET_CLOSED:
will do

2022-03-04 01:50 UTC, jianminzhao commented on Networking/WebSockets/WebSocketImpl.cc
> +            return;
This one basically means not to be called multiple times. Equivalent to current guard with _closed.

2022-03-04 21:56 UTC, borrrden commented on Networking/WebSockets/WebSocketImpl.cc
> +        _socketLCState.store(SOCKET_OPENING);
It was more of just a style comment since `=` is more straightforward than `store` but not a big deal.

2022-03-04 22:03 UTC, borrrden commented on Networking/WebSockets/WebSocketImpl.cc
> +            logInfo("WebSocket already closed or is closing, ignoring onConnect...");
This message doesn't seem to be correct anymore in every case.  If the state is already `OPENED` then the web socket is not "already closed or is closing".  Perhaps the message should be altered:

"WebSocket not in 'opening' state, ignoring onConnect..."

2022-03-04 22:30 UTC, borrrden approved these changes

2022-03-04 23:31 UTC, merged