CBL-2670 : ensure message order for LoopbackWebSocket.
couchbase/couchbase-lite-core pull request #1409
Opened 2022-03-17 20:23 UTC by jianminzhao

LoopbackWebSocket implements messsaging within the same application by threaded queues. For Mac, in particular, we use GCD's dispatch_after in order to simulate network latency. Since dispatch_after takes absolute time in the future, as opposed to a delta delay, the order may be displaced if two future times are numerically equal. To guarantee the ordering, we take advantage of the ordering guarantee of dispatch_async with the serial queue: we queue the messages with dispatch_async, and actually send the message with dispatch_after.

2022-03-17 21:46 UTC, snej requested changes
This fix is correct, but it's only needed in the case where latency is nonzero, i.e. unit tests. Unfortunately it will affect performance in actual (non-test) use, since two async calls are issued instead of one.

I suggest having the `received` method use the old behavior when latency==0 and your new behavior when it's nonzero.

2022-03-17 21:49 UTC, jianminzhao commented
Good point. Will do it.

2022-03-17 22:20 UTC, borrrden commented
I don't understand how this works.  What if you enqueue a message with a delay of 10 seconds, and then enqueue another one with a delay of 5?

Won't this guarantee now that they are in the wrong order?  The will enqueue in the correct order but dequeue in the wrong order.

2022-03-17 22:20 UTC, snej approved these changes

2022-03-17 22:21 UTC, borrrden commented
I don't understand how this works.  Won't this guarantee that things come in the wrong order in the following case?

Add a message for 10 seconds later
Add a message for 5 seconds later

5 seconds later, the enqueueAfter fires and processes the message meant for 10 seconds later.

2022-03-17 22:30 UTC, jianminzhao commented
@borrrden you have a valid point by reading the math locally. However, this is simulating the web socket's latency. By the protocol of web sockets, messages must be received in the order sent.
You are right, latency is a member field of LoopbackWebSocket object. It is supposed to be constant. I probably should emphasize by qualifying it with const.

2022-03-18 00:38 UTC, borrrden approved these changes
Ok with constant latency the route to failure is removed

2022-03-18 02:30 UTC, merged