CBL-3706: Add calls to returnIfCollectionInvalid to CAPI functions.
couchbase/couchbase-lite-core pull request #1582
Opened 2022-09-27 14:11 UTC by callumbirks

CAPI functions using default collection can pass nullptr to other functions if default collection has been deleted, adding call to returnIfCollectionInvalid in these functions stops this from causing any crashes.
Also add tests which call all these functions, after deleting default collection, to reproduce the issue and ensure no crashes occur.

2022-09-27 16:47 UTC, pasin requested changes

2022-09-27 16:47 UTC, pasin commented on C/c4CAPI.cc
> +    returnIfCollectionInvalid(db->getDefaultCollection(), &err, C4Timestamp::Error);
This doesn't solve the problem as calling db->getDefaultCollection() on the next line could still fail. You could get the collection, test it with `returnIfCollectionInvalid()` then use it on the next line.

```
auto collection = db->getDefaultCollection();
returnIfCollectionInvalid(collection, ...);
...
```

2022-09-27 23:41 UTC, borrrden reviewed
Agree with Pasin

2022-09-28 19:27 UTC, pasin commented
@callumbirks if it's ready to re-review, please re-assign.

2022-09-28 19:29 UTC, callumbirks commented
> @callumbirks if it's ready to re-review, please re-assign.

Thanks Pasin, I didn’t even realise I could do that.

2022-09-28 21:11 UTC, pasin approved these changes

2022-09-29 01:14 UTC, borrrden approved these changes

2022-09-29 01:22 UTC, jianminzhao approved these changes

2022-09-29 09:53 UTC, merged