Backport snprintf changes to Lithium.
couchbase/couchbase-lite-core pull request #1586
Opened 2022-09-30 10:01 UTC by callumbirks

Cherry-picked snprintf changes from CBL-3669 onto lithium branch. 
Also did the same for fleece, and updated fleece commit in this branch.

2022-09-30 22:23 UTC, borrrden requested changes
The master branch would have caught this but you have a chicken and egg problem.  You can't point to the PR branch commit of fleece, the PR in fleece needs to be merged first, and then this PR updated to the latest release/lithium fleece

2022-10-03 08:40 UTC, callumbirks commented
> The master branch would have caught this but you have a chicken and egg problem. You can't point to the PR branch commit of fleece, the PR in fleece needs to be merged first, and then this PR updated to the latest release/lithium fleece

Ah I see, thanks Jim 🙂

2022-10-04 16:31 UTC, jianminzhao approved these changes

2022-10-05 01:23 UTC, borrrden requested changes
The latest commit just reset fleece back to where it was, which is also wrong.  This PR needs to point to the current tip of fleece lithium which is `d9ad8314b0c1dc424a9b7d1ec9e88f154ac5923d`

2022-10-06 22:13 UTC, borrrden approved these changes

2022-10-06 22:21 UTC, merged