CBL-4005: Extend tests to multi-collection (II)
couchbase/couchbase-lite-core pull request #1660
Opened 2022-12-14 17:34 UTC by velicuvlad

2022-12-21 18:22 UTC, jianminzhao requested changes

2022-12-21 18:22 UTC, jianminzhao commented on Replicator/tests/ReplicatorCollectionSGTest.cc
>      collNames = {"rose"};
collNames includes other 2 collection names.

2022-12-22 11:13 UTC, velicuvlad commented
Waiting on [CBG-2653](https://issues.couchbase.com/browse/CBG-2653)

2022-12-22 21:31 UTC, jianminzhao approved these changes

2022-12-23 11:53 UTC, merged