Remove API_AVAILABLE annotation for macOS 10.12+ and iOS 10.0+
couchbase/couchbase-lite-core pull request #1808
Opened 2023-06-08 10:29 UTC by velicuvlad

https://issues.couchbase.com/browse/CBL-4519

- removed API_AVAILABLE where version is less than the minimum deployment target

2023-06-08 10:46 UTC, velicuvlad commented
blocked by https://github.com/couchbase/couchbase-lite-core/pull/1807 - will rebase when merged

2023-06-08 18:40 UTC, pasin requested changes

2023-06-08 18:40 UTC, pasin commented on Crypto/PublicKey+Apple.mm
> +            ++gC4ExpectExceptions;  // ignore internal C++ exceptions in Apple Security framework
Remove. Test needs to do this instead.

2023-06-08 18:40 UTC, pasin commented on Crypto/PublicKey+Apple.mm
> +            --gC4ExpectExceptions;
Remove. Test needs to do this instead.

2023-06-08 18:40 UTC, pasin commented on Crypto/PublicKey+Apple.mm
> +                ++gC4ExpectExceptions;
Remove. Test needs to do this instead.

2023-06-08 18:40 UTC, pasin commented on Crypto/PublicKey+Apple.mm
> +                --gC4ExpectExceptions;
Remove. Test needs to do this instead.

2023-06-08 18:40 UTC, pasin commented on Crypto/PublicKey+Apple.mm
> +                ++gC4ExpectExceptions;
Remove. Test needs to do this instead.

2023-06-08 18:40 UTC, pasin commented on Crypto/PublicKey+Apple.mm
> +                --gC4ExpectExceptions;
Remove. Test needs to do this instead.

2023-06-08 18:40 UTC, pasin commented on Crypto/PublicKey+Apple.mm
> +                ++gC4ExpectExceptions;
Remove. Test needs to do this instead.

2023-06-08 18:40 UTC, pasin commented on Crypto/PublicKey+Apple.mm
> +                --gC4ExpectExceptions;
Remove. Test needs to do this instead.

2023-06-08 18:40 UTC, pasin commented on Crypto/PublicKey+Apple.mm
> +            ++gC4ExpectExceptions;
Remove. Test needs to do this instead.

2023-06-08 18:40 UTC, pasin commented on Crypto/PublicKey+Apple.mm
> +            --gC4ExpectExceptions;
Remove. Test needs to do this instead.

2023-06-08 18:40 UTC, pasin commented on Crypto/PublicKey+Apple.mm
> +            ++gC4ExpectExceptions;
Remove. Test needs to do this instead.

2023-06-08 18:40 UTC, pasin commented on Crypto/PublicKey+Apple.mm
> +            --gC4ExpectExceptions;
Remove. Test needs to do this instead.

2023-06-08 21:43 UTC, jianminzhao commented
Approve contingent on Pasin's comments about gC4ExpectExceptions;
API_AVAILABLE is slick. Must be something with objective-c compiler.

2023-06-09 19:55 UTC, pasin approved these changes

2023-06-12 10:38 UTC, merged