Mark return types nullable to avoid Clang UBSan warnings
couchbase/couchbase-lite-core pull request #1821
Opened 2023-06-23 00:09 UTC by snej

I hit a couple of UBSan `_Nonnull binding to null pointer` warnings while running the unit tests with Xcode 14.3. They all stem from API functions that can return NULL but whose return types are not marked `C4NULLABLE`. I've fixed these and other nearby ones I found.

2023-06-23 22:21 UTC, borrrden commented
This failed our new code style validation job, unfortunately.  You should be able to use clang tidy here to figure out what it wants.  Especially since this changes C header formatting I'm worried it will break the .NET generation again.

2023-06-23 22:22 UTC, borrrden requested changes
Let's address the linting job failure

2023-06-23 22:24 UTC, snej commented
Other than inserting some whitespace, the only header changes are adding the `C4NULLABLE` token after some return types. That token already exists on some return types, so I don't think this will cause trouble for .NET.

2023-06-23 23:29 UTC, borrrden commented
I looked at it and I don't think so either.  API is handled in a more resilient way than struct analysis, which is the pain I was remembering (getting two variables on the same line in a struct or enum, etc)

2023-06-26 08:46 UTC, callumbirks commented
I've already filed a ticket for this in Jira, [CBL-4624](https://issues.couchbase.com/browse/CBL-4624), so I guess this can close that.

2023-07-06 02:25 UTC, borrrden approved these changes

2023-07-06 15:16 UTC, merged