CBL-4600: Doc update c4repl_start
couchbase/couchbase-lite-core pull request #1825
Opened 2023-06-27 17:20 UTC by jianminzhao

Added the following
```
\note This function may perform action in the calling thread that requires the transaction from the database
              that was passed to the replicator instance, \p repl.
```
I merely note the fact that is critical to the user I assume that general prerequisite knowledge in using the library that they cannot open a transaction inside a transaction.

2023-06-28 00:07 UTC, borrrden requested changes
This is kind of a word salad.  It's hard to follow even if you know the situation, and I think it will be impossible to follow if you don't.  Try to be clear about what to avoid.

2023-06-28 12:04 UTC, velicuvlad commented
Maybe something like `If this function is called while a transaction is open on the same database it will deadlock, as it trying to acquire the same database` ... maybe worth specifying that this is considered transaction as well (starting the repl)...?

2023-06-28 18:20 UTC, jianminzhao commented
Simplified wording. Thanks to @velicuvlad for the suggestion. I avoided emphasizing the "same thread," because it makes the doc unnecessary complicated and why people want to do transaction in another thread while calling this function. If you think we should limit the "Do not" to the "same thread," I can change it.

2023-06-28 22:10 UTC, borrrden approved these changes

2023-06-29 06:15 UTC, pasin approved these changes

2023-06-29 10:36 UTC, callumbirks approved these changes

2023-06-29 10:42 UTC, velicuvlad approved these changes

2023-06-29 16:40 UTC, merged