CBL-5936: IndexUpdater's finish() returns an error when there are any null vector set
couchbase/couchbase-lite-core pull request #2086
Opened 2024-06-28 11:28 UTC by callumbirks

I added in the `modified` property to the IndexUpdater's `Item`, this allows us to check that all vectors have been modified in some way without checking `vector != nullptr`, because any vector set to null would break that condition.

2024-06-28 18:12 UTC, jianminzhao requested changes

2024-06-28 18:12 UTC, jianminzhao commented on LiteCore/Query/LazyIndex.hh
> +        enum class ItemStatus {
it can be ItemStatus :  uint8_t

2024-06-28 18:20 UTC, callumbirks commented on LiteCore/Query/LazyIndex.hh
> +        enum class ItemStatus {
Why?

2024-06-29 00:29 UTC, jianminzhao approved these changes

2024-06-29 00:37 UTC, merged