CBL-6207: Test multi-level unnest w/o index.
couchbase/couchbase-lite-core pull request #2137
Opened 2024-09-13 01:01 UTC by jianminzhao

The tests come from the API Specification.

Note that "group-by" does not work with unnest without index.

2024-09-16 21:42 UTC, borrrden approved these changes

2024-09-17 00:24 UTC, pasin requested changes

2024-09-17 00:24 UTC, pasin commented on LiteCore/tests/QueryTest.cc
> +        });
Can we just json string instead of the code above for readability?

2024-09-18 16:12 UTC, pasin approved these changes

2024-09-18 16:37 UTC, merged